### ISSUE TITLE
after run build scirpt, got  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL error

### ISSUE THREAD

**Issue by sedationh** [pg-nano/pg-nano#35]
```
repos/pg-nano - (master) > pnpm run build

> pg-nano@0.1.0-beta.7 build /Users/seda/workspace/repos/pg-nano
> pnpm -s build:native && tinyrun --names core,plugins 'pnpm -s build:core' 'pnpm --stream --filter=@pg-nano/plugin-* build'

   core started pid=25837
plugins started pid=25838
plugins Scope: 3 of 19 workspace projects
plugins plugins/match build$ rimraf dist && tsup
plugins plugins/typebox build$ rimraf dist && tsup
plugins plugins/crud build$ rimraf dist && tsup
plugins plugins/crud build: CLI Building entry: src/plugin.ts, src/field-mappers.ts
plugins plugins/crud build: CLI Using tsconfig: tsconfig.json
plugins plugins/crud build: CLI tsup v8.2.4
plugins plugins/crud build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/crud/tsup.config.ts
plugins plugins/match build: CLI Building entry: src/plugin.ts, src/params.ts
plugins plugins/match build: CLI Using tsconfig: ../../tsconfig.json
plugins plugins/match build: CLI tsup v8.2.4
plugins plugins/match build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/match/tsup.config.ts
plugins plugins/match build: CLI Target: esnext
plugins plugins/match build: ESM Build start
plugins plugins/crud build: CLI Target: esnext
plugins plugins/typebox build: CLI Building entry: src/plugin.ts, src/types.ts
plugins plugins/typebox build: CLI Using tsconfig: tsconfig.json
plugins plugins/typebox build: CLI tsup v8.2.4
plugins plugins/typebox build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/typebox/tsup.config.ts
plugins plugins/crud build: ESM Build start
plugins plugins/typebox build: CLI Target: esnext
plugins plugins/typebox build: ESM Build start
plugins plugins/match build: ESM dist/params.js 0 B
plugins plugins/match build: ESM dist/plugin.js 8.28 KB
plugins plugins/match build: ESM ⚡️ Build success in 15ms
plugins plugins/match build: Done
   core CLI Building entry: {"pg-nano":"src/core/mod.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"pg-nano/config":"src/config/config.ts","pg-nano/plugin":"src/plugin/plugin.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"main":"src/cli/main.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"index":"packages/pg-native/src/index.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI Target: esnext
plugins plugins/crud build: ESM dist/field-mappers.js 544.00 B
plugins plugins/crud build: ESM dist/plugin.js        5.54 KB
plugins plugins/crud build: ESM ⚡️ Build success in 50ms
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
plugins plugins/typebox build: ESM dist/types.js  1.53 KB
plugins plugins/typebox build: ESM dist/plugin.js 33.23 KB
plugins plugins/typebox build: ESM ⚡️ Build success in 126ms
   core ESM dist/pg-nano/plugin.js 1.37 KB
   core ESM dist/pg-nano/config.js 2.14 KB
   core ESM ⚡️ Build success in 73ms
   core ESM dist/pg-nano.js 15.77 KB
   core ESM ⚡️ Build success in 184ms
plugins plugins/typebox build: DTS Build start
plugins plugins/crud build: DTS Build start
   core ESM dist/node_modules/pg-native/index.js 35.94 KB
   core ESM ⚡️ Build success in 241ms
   core "buildResult" is imported from external module "pg-native" but never used in "dist/pg-nano/cli/dev-2PS5Q6TS.js".
   core DTS Build start
   core DTS Build start
   core DTS Build start
   core ESM dist/pg-nano/cli/main.js           848.00 B
   core ESM dist/pg-nano/cli/dev-2PS5Q6TS.js   51.33 KB
   core ESM dist/pg-nano/cli/init-UL4AKY7R.js  766.00 B
   core ESM dist/pg-nano/cli/chunk-LCLPTRZS.js 5.95 KB
   core ESM dist/pg-nano/cli/chunk-RH73SNSC.js 2.84 KB
   core ESM dist/pg-nano/cli/chunk-6FALZG4H.js 927.00 B
   core ESM ⚡️ Build success in 416ms
   core DTS ⚡️ Build success in 1631ms
   core DTS dist/node_modules/pg-native/index.d.ts 17.22 KB
   core DTS ⚡️ Build success in 1721ms
   core DTS dist/pg-nano.d.ts 12.81 KB
   core DTS ⚡️ Build success in 2250ms
   core DTS dist/pg-nano/plugin.d.ts  869.00 B
   core DTS dist/pg-nano/config.d.ts  232.00 B
   core DTS dist/config-r484h7NV.d.ts 19.18 KB
   core
   core
   core cmd='pnpm -s build:core' exitCode=0 signalCode=null duration=3s
plugins plugins/crud build: DTS ⚡️ Build success in 2411ms
plugins plugins/crud build: DTS dist/plugin.d.ts        124.00 B
plugins plugins/crud build: DTS dist/field-mappers.d.ts 8.67 KB
plugins plugins/crud build: Done
plugins plugins/typebox build: Error parsing: /Users/seda/workspace/repos/pg-nano/packages/postgres-range/src/index.ts:1:7
plugins plugins/typebox build: Error: error occured in dts build
plugins plugins/typebox build:     at Worker.<anonymous> (/Users/seda/workspace/repos/pg-nano/node_modules/.pnpm/tsup@8.2.4_jiti@1.21.6_postcss@8.4.45_typescript@5.5.4/node_modules/tsup/dist/index.js:1539:26)
plugins plugins/typebox build:     at Worker.emit (node:events:518:28)
plugins plugins/typebox build:     at MessagePort.<anonymous> (node:internal/worker:263:53)
plugins plugins/typebox build:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
plugins plugins/typebox build:     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
plugins plugins/typebox build: DTS Build error
plugins plugins/typebox build: Failed
plugins /Users/seda/workspace/repos/pg-nano/plugins/typebox:
plugins  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @pg-nano/plugin-typebox@0.1.0-beta.2 build: `rimraf dist && tsup`
plugins Exit status 1
plugins
plugins
plugins cmd='pnpm --stream --filter=@pg-nano/plugin-* build' exitCode=1 signalCode=null duration=3s
repos/pg-nano - (master) > export NODE_OPTIONS="--max-old-space-size=8192"
repos/pg-nano - (master) > pnpm run build

> pg-nano@0.1.0-beta.7 build /Users/seda/workspace/repos/pg-nano
> pnpm -s build:native && tinyrun --names core,plugins 'pnpm -s build:core' 'pnpm --stream --filter=@pg-nano/plugin-* build'

   core started pid=28324
plugins started pid=28325
plugins Scope: 3 of 19 workspace projects
plugins plugins/crud build$ rimraf dist && tsup
plugins plugins/match build$ rimraf dist && tsup
plugins plugins/typebox build$ rimraf dist && tsup
plugins plugins/crud build: CLI Building entry: src/plugin.ts, src/field-mappers.ts
plugins plugins/crud build: CLI Using tsconfig: tsconfig.json
plugins plugins/crud build: CLI tsup v8.2.4
plugins plugins/crud build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/crud/tsup.config.ts
plugins plugins/typebox build: CLI Building entry: src/plugin.ts, src/types.ts
plugins plugins/typebox build: CLI Using tsconfig: tsconfig.json
plugins plugins/typebox build: CLI tsup v8.2.4
plugins plugins/typebox build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/typebox/tsup.config.ts
plugins plugins/typebox build: CLI Target: esnext
plugins plugins/typebox build: ESM Build start
plugins plugins/crud build: CLI Target: esnext
plugins plugins/crud build: ESM Build start
plugins plugins/match build: CLI Building entry: src/plugin.ts, src/params.ts
plugins plugins/match build: CLI Using tsconfig: ../../tsconfig.json
plugins plugins/match build: CLI tsup v8.2.4
plugins plugins/match build: CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/plugins/match/tsup.config.ts
plugins plugins/match build: CLI Target: esnext
plugins plugins/match build: ESM Build start
plugins plugins/match build: ESM dist/params.js 0 B
plugins plugins/match build: ESM dist/plugin.js 8.28 KB
plugins plugins/match build: ESM ⚡️ Build success in 16ms
plugins plugins/match build: Done
   core CLI Building entry: {"pg-nano":"src/core/mod.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"pg-nano/config":"src/config/config.ts","pg-nano/plugin":"src/plugin/plugin.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"main":"src/cli/main.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI Building entry: {"index":"packages/pg-native/src/index.ts"}
   core CLI Using tsconfig: tsconfig.json
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI tsup v8.2.4
   core CLI Using tsup config: /Users/seda/workspace/repos/pg-nano/tsup.config.ts
   core CLI Target: esnext
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
   core CLI Target: esnext
   core ESM Build start
plugins plugins/crud build: ESM dist/field-mappers.js 544.00 B
plugins plugins/crud build: ESM dist/plugin.js        5.54 KB
plugins plugins/crud build: ESM ⚡️ Build success in 64ms
plugins plugins/typebox build: ESM dist/types.js  1.53 KB
plugins plugins/typebox build: ESM dist/plugin.js 33.23 KB
plugins plugins/typebox build: ESM ⚡️ Build success in 104ms
   core ESM dist/pg-nano/plugin.js 1.37 KB
   core ESM dist/pg-nano/config.js 2.14 KB
   core ESM ⚡️ Build success in 86ms
plugins plugins/crud build: DTS Build start
plugins plugins/typebox build: DTS Build start
   core "buildResult" is imported from external module "pg-native" but never used in "dist/pg-nano/cli/dev-2PS5Q6TS.js".
   core ESM dist/pg-nano.js 15.77 KB
   core ESM ⚡️ Build success in 266ms
   core ESM dist/pg-nano/cli/main.js           848.00 B
   core ESM dist/pg-nano/cli/init-UL4AKY7R.js  766.00 B
   core ESM dist/pg-nano/cli/chunk-RH73SNSC.js 2.84 KB
   core ESM dist/pg-nano/cli/chunk-6FALZG4H.js 927.00 B
   core ESM dist/pg-nano/cli/chunk-LCLPTRZS.js 5.95 KB
   core ESM dist/pg-nano/cli/dev-2PS5Q6TS.js   51.33 KB
   core ESM ⚡️ Build success in 263ms
   core DTS Build start
   core DTS Build start
   core DTS Build start
   core ESM dist/node_modules/pg-native/index.js 35.94 KB
   core ESM ⚡️ Build success in 384ms
   core DTS ⚡️ Build success in 1396ms
   core DTS dist/node_modules/pg-native/index.d.ts 17.22 KB
   core DTS ⚡️ Build success in 1551ms
   core DTS dist/pg-nano.d.ts 12.81 KB
   core DTS ⚡️ Build success in 1986ms
   core DTS dist/pg-nano/plugin.d.ts  869.00 B
   core DTS dist/pg-nano/config.d.ts  232.00 B
   core DTS dist/config-r484h7NV.d.ts 19.18 KB
   core
   core
   core cmd='pnpm -s build:core' exitCode=0 signalCode=null duration=3s
plugins plugins/crud build: DTS ⚡️ Build success in 2157ms
plugins plugins/crud build: DTS dist/plugin.d.ts        124.00 B
plugins plugins/crud build: DTS dist/field-mappers.d.ts 8.67 KB
plugins plugins/crud build: Done
plugins plugins/typebox build: Error parsing: /Users/seda/workspace/repos/pg-nano/packages/postgres-range/src/index.ts:1:7
plugins plugins/typebox build: Error: error occured in dts build
plugins plugins/typebox build:     at Worker.<anonymous> (/Users/seda/workspace/repos/pg-nano/node_modules/.pnpm/tsup@8.2.4_jiti@1.21.6_postcss@8.4.45_typescript@5.5.4/node_modules/tsup/dist/index.js:1539:26)
plugins plugins/typebox build:     at Worker.emit (node:events:518:28)
plugins plugins/typebox build:     at MessagePort.<anonymous> (node:internal/worker:263:53)
plugins plugins/typebox build:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
plugins plugins/typebox build:     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
plugins plugins/typebox build: DTS Build error
plugins plugins/typebox build: Failed
plugins /Users/seda/workspace/repos/pg-nano/plugins/typebox:
plugins  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @pg-nano/plugin-typebox@0.1.0-beta.2 build: `rimraf dist && tsup`
plugins Exit status 1
plugins
plugins
plugins cmd='pnpm --stream --filter=@pg-nano/plugin-* build' exitCode=1 signalCode=null duration=3s
```

```
repos/pg-nano - (master) > node --version && pnpm --version
v20.12.2
9.9.0
```

I have tired `export NODE_OPTIONS="--max-old-space-size=8192"` before run `pnpm run build`, but cant work
https://github.com/directus/directus/discussions/15392#discussioncomment-3546812

I am using Apple M2

**Comment by aleclarson** [comment]
It should be fixed. Thanks for catching this

**Comment by aleclarson** [comment]
I'm going to rework the build script. One sec
